server:
  port: 8202
spring:
  application:
    name: ribbon-service2
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8001/eureka/
ribbon:
  ConnectTimeout: 3000 #服务请求连接超时时间（毫秒）
  ReadTimeout: 1000 #服务请求处理超时时间（毫秒）
  MaxAutoRetries: 0 #同一实例最大重试次数，不包括首次调用。默认值为0
  MaxAutoRetriesNextServer: 0 #同一个服务其他实例的最大重试次数，不包括第一次调用的实例。默认值为1
  OkToRetryOnAllOperations: false #是否所有操作都允许重试。默认值为false
  http:
    client:
      enabled: true
service-url:
  user-service: http://ribbon-service1/ribbon/service1/user
