server:
  port: 9203
spring:
  application:
    name: gateway-service3
  cloud:
    consul: #Consul服务注册发现配置
      host: localhost
      port: 8500
      discovery:
        service-name: ${spring.application.name}