server:
  port: 8207
spring:
  application:
    name: consul-service2
  cloud:
    consul: #Consul服务注册发现配置
      host: localhost
      port: 8500
      discovery:
        service-name: ${spring.application.name}