server:
  port: 9201
spring:
  cloud:
    gateway:
      routes:
        - id: gateway-service3
          uri: http://localhost:9203 #匹配后路由地址
          predicates:
            - After=2022-01-25T14:30:00+08:00[Asia/Shanghai] #在指定时间之后的请求会匹配该路由