server:
  port: 9201
spring:
  application:
    name: gateway-service
  cloud:
    consul: #Consul服务注册发现配置
      host: localhost
      port: 8500
      discovery:
        service-name: ${spring.application.name}
    gateway:
      routes:
        - id: gateway-service3 #路由的ID
          uri: http://localhost:9203 #匹配后路由地址
          predicates: # 断言，路径相匹配的进行路由
            - Path=/gateway/service3/**